#!/bin/bash

set -eu

# Usage: ./release <VERSION> | sh -

grep '\[x\.x\.x\] - xxxx-xx-xx' CHANGELOG.md
sed -E -i "s/\[x\.x\.x\]/\[$1\]/" CHANGELOG.md
sed -E -i "s/xxxx-xx-xx/$(date --iso-8601)/" CHANGELOG.md
sed -E -i "s/(version:[ ]*[ ^])(.*)/\1$1/" package.yaml
sed -E -i "s/(cilly-)([^ \n]*)/\1$1/" 3-PARTY-NOTICES.md
sed -i -E \
  's|(cillyHelperImage = "lunkentuss/cilly-helper:).*"|\1'"$1"'"|' \
  src/Main.hs

make cilly.cabal

echo "git commit -am 'release: v$1'"
echo "git tag -a 'v$1' -m 'v$1'"
echo "git push --atomic origin master 'v$1'"
