#!/bin/bash

set -eu

# Usage: ./release <VERSION> | sh -

hpack
sed -E -i "s/(version:[ ]*[ ^])(.*)/\1$1/" package.yaml
sed -E -i "s/(cilly-)([^ \n]*)/\1$1/" 3-PARTY-NOTICES.md
sed -i -E \
  's|(cillyHelperImage = "lunkentuss/cilly-helper:).*"|\1'"$1"'"|' \
  src/Main.hs

echo "git commit -am 'release: v$1'"
echo "git tag -a 'v$1' -m 'v$1'"
echo "git push --atomic origin master 'v$1'"
