#!/bin/bash

set -eux

nix build .#cilly-helper-container
image="$(docker load < result | sed -E 's|Loaded image: (.*)|\1|')"

cilly_helper_hash="$(
  nix derivation show .#cilly-helper-container \
    | jq -r '.[].outputs.out.path' \
    | sed -E 's|/nix/store/([^-]*).*|\1|' \
)"
echo "$cilly_helper_hash"
sed -i -E \
  's|(cillyHelperImage = "lunkentuss/cilly-helper:).*"|\1'"$cilly_helper_hash"'"|' \
  src/Main.hs

docker tag "$image" "lunkentuss/cilly-helper:$cilly_helper_hash"
