#!/bin/bash

# shellcheck disable=SC2086

set -euo pipefail

nix_build_arg="$1"
image="$2"

skopeo \
  login \
  "docker.io" \
  --username "$REGISTRY_USER" \
  --password "$REGISTRY_PASSWORD"

nix \
  build \
  "$nix_build_arg"

skopeo \
	--insecure-policy \
	copy \
	"docker-archive://$(realpath result)" \
	"docker://$image"
